apiVersion: apps/v1
kind: Deployment
metadata: 
  name: posts-depl # Name of deployment
spec:
  replicas: 1 # Number of pods we want to create running some particular image
  selector: 
    matchLabels:
      app: posts
  template:
    metadata:
      labels:
        app: posts
    spec:
      containers:
        - name: posts
          image: services/posts:0.0.1

# selector - Take a look at all the different pods that have been created
# find all the pods with a label of app posts.

# template - The template is where we specify the exact configuration of a pod